version: "3.5"

services:
  debug-proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DOWNSTREAM_HOST: dummy
      DOWNSTREAM_PORT: 80
      PORT: "${PORT:?err}"
    ports:
      - "8080:${PORT:?err}"
    restart: always
  dummy:
    image: nginx:latest
    depends_on:
      - debug-proxy
